import { ScheduleResponse } from '@/types/schedule';

export const mockData: ScheduleResponse = {
  activities: [
    {
      id: 'gym-1',
      name: 'Gym',
      category: 'gym',
      days: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
      startTime: '03:45',
      endTime: '05:45',
      color: '#fef3c7',
    },
    {
      id: 'ai-1',
      name: 'AI Learning',
      category: 'ai-learning',
      days: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      startTime: '06:15',
      endTime: '06:45',
      color: '#dbeafe',
    },
    {
      id: 'breakfast-1',
      name: 'Breakfast',
      category: 'breakfast',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      startTime: '06:45',
      endTime: '07:15',
      color: '#fef9c3',
    },
    {
      id: 'commute-1',
      name: 'Commute',
      category: 'commute',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '09:00',
      endTime: '09:45',
      color: '#d1f4e0',
    },
    {
      id: 'work-1',
      name: 'Office',
      category: 'office',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      startTime: '10:00',
      endTime: '17:00',
      color: '#e0e7ff',
    },
    {
      id: 'family-1',
      name: 'Family Time',
      category: 'family',
      days: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      startTime: '18:00',
      endTime: '21:00',
      color: '#fecaca',
    },
  ],
  weeklyGoals: [],
};
